### PR TITLE
Installing the project updates package-lock.json

### PR DESCRIPTION
**Pull request by chriscn**
*Description of changes goes here!*

## Version:

Which version does this Pull Request Target?

## Checklist:

*Add any outstanding items to this checklist, but don't delete the default options*

- [ ] Updates documentation (if so - is it in this PR, or on the v2 branch?)
- [ ] Tested locally

### CODE REVIEW

**Comment by chriscn** [comment]
@Jbithell not sure what stance you want to take regarding this; I just was working on some project and there were a lot of changes so I thought a seperate PR would have been better.

**Comment by Jbithell** [comment]
@chriscn to be honest.... this prompts me to remove the lockfile! I don't really see the use in having one here but welcome your thoughts. It was just added when we added a root package.json as a convinience feature for development (I think!)

**Comment by chriscn** [comment]
@Jbithell according to this [answer](https://stackoverflow.com/a/56254478) it should be committed. But will required to be updated. I would keep it as such. May need updating commands with `npm ci`

**Comment by Jbithell** [comment]
> @Jbithell according to this [answer](https://stackoverflow.com/a/56254478) it should be committed. But will required to be updated. I would keep it as such. May need updating commands with `npm ci`

`package-lock.json` has huge value and we keep all three of them in source control for each of the three projects in this repo - I'm just suggesting that maintaining a 4th that duplicates the three of them is extra work that most of us will forget to do (as the existence of your PR demonstrates!) especially given it isn't really used by anyone/anything except one or two of the contributors who prefer it over using the individual `package.json` files in each of three folders in the monorepo.

**Review by Jbithell — APPROVED** [review]

**Pull request merged**
